#!/bin/sh
SERVICE_NAME=business_python

case $1 in
      start)
         echo "Starting $SERVICE_NAME....."
        cd /home/business_python/business_python/
        source /home/business_python/business_python/env/bin/activate
        nohup python /home/business_python/business_python/manage.py runserver 0.0.0.0:9100 &
        echo -ne '\n'| echo "Service is Running"
        echo -ne '\n'| echo "Completed"

   exit 0
    ;;

      stop)
        echo -e "Stopping process pid `ps -ef | grep "python /home/business_python/manage.py runserver" |grep -v grep | awk {'print $2'}`\n"
        ps -ef | grep "python /home/business_python/business_python/manage.py runserver" |grep -v grep | awk {'print $2'} | xargs kill -9
        echo "Stoping $SERVICE_NAME"
      ;;

     restart)

        echo "Stop business_python"
        echo -e "Stopping process pid `ps -ef | grep "python /home/business_python/manage.py runserver" |grep -v grep | awk {'print $2'}`\n"
        ps -ef | grep "python /home/business_python/business_python/manage.py runserver" |grep -v grep | awk {'print $2'} | xargs kill -9
        cd /home/business_python/business_python/
        source /home/business_python/business_python/env/bin/activate
        echo -e "Starting business_python"
        nohup python /home/business_python/business_python/manage.py runserver 0.0.0.0:9100 &
        echo -ne '\n'| echo "Restarting"
        echo -ne '\n'| echo "Completed"
     ;;
esac

