#!/bin/sh
SERVICE_NAME=businessapi

case $1 in
      start)
         echo "Starting $SERVICE_NAME....."
        cd /home/businessapi/businessapi/
        source /home/businessapi/businessapi/env/bin/activate
        nohup python /home/businessapi/businessapi/manage.py runserver 0.0.0.0:9000 &
        echo -ne '\n'| echo "Service is Running"
        echo -ne '\n'| echo "Completed"
   exit 0
    ;;

      stop)
        echo -e "Stopping process pid `ps -ef | grep "python /home/businessapi/manage.py runserver" |grep -v grep | awk {'print $2'}`\n"
        ps -ef | grep "python /home/businessapi/businessapi/manage.py runserver" |grep -v grep | awk {'print $2'} | xargs kill -9
        echo "Stoping $SERVICE_NAME"
      ;;

     restart)

        echo "Stop businessapi"
        echo -e "Stopping process pid `ps -ef | grep "python /home/businessapi/manage.py runserver" |grep -v grep | awk {'print $2'}`\n"
        ps -ef | grep "python /home/businessapi/businessapi/manage.py runserver" |grep -v grep | awk {'print $2'} | xargs kill -9
        cd /home/businessapi/businessapi/
        source /home/businessapi/businessapi/env/bin/activate
        echo -e "Starting businessapi"
        nohup python /home/businessapi/businessapi/manage.py runserver 0.0.0.0:9000 &
        echo -ne '\n'| echo "Restarting"
        echo -ne '\n'| echo "Completed" 

       ;;
esac

